name: The program crashes, hangs, certain function does not work / Program çöküyor, donuyor, belirli bir işlev çalışmıyor
description: File a bug report / Bir hata bildirimi yapın

body:
  - type: markdown
    attributes:
      value: |
        ### Carefully read all the text IN FULL. Take this seriously.
        ### Use this form only for software bug reports! The website does not open? That's likely NOT a bug, do NOT report it here! You have a question regarding the program? That's not a bug either!
        #### If in doubt, [use NTC.party forum](https://ntc.party/c/community-software/goodbyedpi).
        ### Aşağıdaki metni TAMAMEN dikkatlice okuyun. Bu konuya ciddi bir şekilde yaklaşın.
        ### Bu formu yalnızca yazılım hatalarını bildirmek için kullanın! Web sitesi açılmıyor mu? Bu büyük ihtimalle bir hata değildir, buradan bildirmeyin! Programla ilgili bir sorunuz mu var? Bu da bir hata değildir!
        #### Şüpheniz varsa, [NTC.party forumunu kullanın](https://ntc.party/c/community-software/goodbyedpi).

        GoodbyeDPI does not guarantee to work with your ISP for every blocked website or at all. If GoodbyeDPI can't unblock some or any websites, this is most likely not a software bug, and you should not report it here.

        Please only report software bugs, such as:
          * program crash
          * incorrect network packet handling
          * antivirus incompatibility
          * DNS redirection problems
          * memory leaks
          * other software issues

        Please make sure to check other opened and closed issues, it could be your bug has been reported already.
        For questions, or if in doubt, [use NTC.party forum](https://ntc.party/c/community-software/goodbyedpi).

        ### BU FORMU SADECE HATALAR İÇİN KULLANIN! Web sitesi açılmıyor mu? Bu büyük ihtimalle bir hata değildir, buradan bildirmeyin!
        GoodbyeDPI’nin, sağlayıcınızla %100 uyumlu çalışacağını veya her engelli siteyi açacağını garanti etmez. Eğer GoodbyeDPI bazı ya da hiçbir web sitesini açamıyorsa, büyük ihtimalle bu bir yazılım hatası değildir ve bunu buradan bildirmemelisiniz.

        Lütfen yalnızca yazılım hatalarını bildirin, örneğin:
          * programın çökmesi
          * ağ paketlerinin hatalı işlenmesi
          * antivirüs uyumsuzluğu
          * DNS yönlendirme problemleri
          * bellek sızıntıları
          * diğer yazılım sorunları

        Ayrıca, diğer açık ve kapalı sorunlara göz atın. Sorununuz daha önce bildirilmiş ya da düzeltilmiş olabilir.
        Sorularınız veya şüpheleriniz varsa [NTC.party forumunu kullanın](https://ntc.party/c/community-software/goodbyedpi).
  - type: checkboxes
    id: terms
    attributes:
      label: CAPTCHA
      description: Confirm that you have read the text above / Yukarıdaki metni okuduğunuzu onaylayın
      options:
        - label: I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Soruları veya “çalışmayan web sitesi” raporlarını buradan bildirerek, sorunlar bölümünü kötüye kullanırsam depodan engellenebileceğimi anlıyorum.
          required: true
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating system / İşletim sistemi
      description: Enter your Windows version. For Windows 10 and 11 include build/update number.
      placeholder: örn. Windows 10 20H2
    validations:
      required: true
  - type: dropdown
    id: is-svc
    attributes:
      label: Running as service / Servis olarak çalıştırma
      description: Do you use GoodbyeDPI as a Windows Service?
      options:
        - I run it as a regular program / Programı normal bir şekilde çalıştırıyorum
        - I installed it as a service / Windows hizmeti olarak kurdum
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug / Hata açıklaması
      description: A clear and concise description of what the bug is / Hatanın ne olduğu hakkında net ve ayrıntılı bir açıklama yapın
      placeholder: Daha net açıklamak için ekran görüntüleri ekleyin / Gerekirse ekran görüntüleri ekleyin
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information / Ek bilgiler
      description: If you have a hints on why this bug happens, you can express it here / Bu hatanın neden meydana geldiğine dair ipuçlarınız varsa, burada belirtebilirsiniz
