name: Feature request / Yeni özellik talebi
description: Suggest an idea or function for this project / Bu proje için bir fikir veya işlev önerin

body:
  - type: markdown
    attributes:
      value: |
        If you think of a great function or circumvention method which is missing from the program, go ahead and suggest it here. But first make sure to search existing tickets.
        Eğer programda eksik olduğunu düşündüğünüz harika bir işlev veya engelleme aşma yöntemi aklınıza gelirse, bunu burada önerin. Ancak önce mevcut talepleri arayarak böyle bir önerinin daha önce yapılmadığından emin olun.
  - type: checkboxes
    id: ensure
    attributes:
      label: I've made sure there's no existing feature request / Böyle bir özelliğin daha önce önerilmediğinden emin oldum
      options:
        - label: I've made sure there's no existing feature request / Böyle bir özelliğin daha önce önerilmediğinden emin oldum
          required: true
  - type: textarea
    id: description
    attributes:
      label: Describe your feature / Önerinizi açıklayın
    validations:
      required: true
